### ISSUE TITLE
[1.16.5] Language packs missing for k_turrets.integrity in English

### ISSUE THREAD

**Issue by NighthowlerStudios** [AlexiyOrlov/k-turrets#26]
This isn't the only time language stuff has suddenly gone missing either when you've added new features or removed any.  If you need someone to help you with the English translations, I wouldn't mind just submitting pull requests from now on, if it is easier for you that way.

**Comment by AlexiyOrlov** [comment]
I fixed it. Reason for keys missing is because in 1.16.5, the mod id "k-turrets", not "k_turrets" as in later versions, so I sometimes overlook this when backporting features.
You are welcome to make pull requests because I usually play/test the latest versions the most and backport features to older versions,
